VERSION 0.8

# Global default arguments.
ARG --global DOCKER_REPO = "ronkitay"
ARG --global RELEASE = "0.1.4"
ARG --global ALPINE_VERSION = "3.15.2"
ARG --global DEBIAN_VERSION = "bookworm"
ARG --global TAG_SUFFIX = ""

# Base images (no local dependencies)
basic-env:
    FROM DOCKERFILE ./basic-env --build-arg DEBIAN_VERSION=$DEBIAN_VERSION
    SAVE IMAGE $DOCKER_REPO/basic-env:$RELEASE$TAG_SUFFIX

duckdb:
    FROM DOCKERFILE ./duckdb --build-arg DEBIAN_VERSION=$DEBIAN_VERSION
    SAVE IMAGE $DOCKER_REPO/duckdb:$RELEASE$TAG_SUFFIX

mongo-client:
    FROM DOCKERFILE ./mongo-client --build-arg DEBIAN_VERSION=$DEBIAN_VERSION
    SAVE IMAGE $DOCKER_REPO/mongo-client:$RELEASE$TAG_SUFFIX

mysql-cli:
    FROM DOCKERFILE ./mysql-cli --build-arg DEBIAN_VERSION=$DEBIAN_VERSION
    SAVE IMAGE $DOCKER_REPO/mysql-cli:$RELEASE$TAG_SUFFIX

postgres-cli:
    FROM DOCKERFILE ./postgres-cli --build-arg DEBIAN_VERSION=$DEBIAN_VERSION
    SAVE IMAGE $DOCKER_REPO/postgres-cli:$RELEASE$TAG_SUFFIX

# Level 1 dependencies
python-3-env:
    BUILD --build-arg DEBIAN_VERSION=$DEBIAN_VERSION --build-arg RELEASE=$RELEASE --build-arg TAG_SUFFIX=$TAG_SUFFIX --build-arg DOCKER_REPO=$DOCKER_REPO +basic-env
    FROM DOCKERFILE ./python-3-env --RELEASE=$RELEASE --DOCKER_REPO=$DOCKER_REPO
    SAVE IMAGE $DOCKER_REPO/python-3-env:$RELEASE$TAG_SUFFIX

k8s-cli:
    BUILD --build-arg DEBIAN_VERSION=$DEBIAN_VERSION --build-arg RELEASE=$RELEASE --build-arg TAG_SUFFIX=$TAG_SUFFIX --build-arg DOCKER_REPO=$DOCKER_REPO +basic-env
    FROM DOCKERFILE ./k8s-cli --RELEASE=$RELEASE --DOCKER_REPO=$DOCKER_REPO
    SAVE IMAGE $DOCKER_REPO/k8s-cli:$RELEASE$TAG_SUFFIX

go-env:
    BUILD --build-arg DEBIAN_VERSION=$DEBIAN_VERSION --build-arg RELEASE=$RELEASE --build-arg TAG_SUFFIX=$TAG_SUFFIX --build-arg DOCKER_REPO=$DOCKER_REPO +basic-env
    FROM DOCKERFILE ./go-env --RELEASE=$RELEASE --DOCKER_REPO=$DOCKER_REPO
    SAVE IMAGE $DOCKER_REPO/go-env:$RELEASE$TAG_SUFFIX

jsqsh:
    BUILD --build-arg DEBIAN_VERSION=$DEBIAN_VERSION --build-arg RELEASE=$RELEASE --build-arg TAG_SUFFIX=$TAG_SUFFIX --build-arg DOCKER_REPO=$DOCKER_REPO +basic-env
    FROM DOCKERFILE ./jsqsh --RELEASE=$RELEASE --DOCKER_REPO=$DOCKER_REPO
    SAVE IMAGE $DOCKER_REPO/jsqsh:$RELEASE$TAG_SUFFIX

lua-5.4-env: 
    BUILD --build-arg DEBIAN_VERSION=$DEBIAN_VERSION --build-arg RELEASE=$RELEASE --build-arg TAG_SUFFIX=$TAG_SUFFIX --build-arg DOCKER_REPO=$DOCKER_REPO +basic-env
    FROM DOCKERFILE ./lua-5.4-env --RELEASE=$RELEASE --DOCKER_REPO=$DOCKER_REPO
    SAVE IMAGE $DOCKER_REPO/lua-5.4-env:$RELEASE$TAG_SUFFIX

node-14-env:
    BUILD --build-arg DEBIAN_VERSION=$DEBIAN_VERSION --build-arg RELEASE=$RELEASE --build-arg TAG_SUFFIX=$TAG_SUFFIX --build-arg DOCKER_REPO=$DOCKER_REPO +basic-env
    FROM DOCKERFILE ./node-14-env --RELEASE=$RELEASE --DOCKER_REPO=$DOCKER_REPO
    SAVE IMAGE $DOCKER_REPO/node-14-env:$RELEASE$TAG_SUFFIX

node-16-env:
    BUILD --build-arg DEBIAN_VERSION=$DEBIAN_VERSION --build-arg RELEASE=$RELEASE --build-arg TAG_SUFFIX=$TAG_SUFFIX --build-arg DOCKER_REPO=$DOCKER_REPO +basic-env
    FROM DOCKERFILE ./node-16-env --RELEASE=$RELEASE --DOCKER_REPO=$DOCKER_REPO
    SAVE IMAGE $DOCKER_REPO/node-16-env:$RELEASE$TAG_SUFFIX

rust-env:
    BUILD --build-arg DEBIAN_VERSION=$DEBIAN_VERSION --build-arg RELEASE=$RELEASE --build-arg TAG_SUFFIX=$TAG_SUFFIX --build-arg DOCKER_REPO=$DOCKER_REPO +basic-env
    FROM DOCKERFILE ./rust-env --RELEASE=$RELEASE --DOCKER_REPO=$DOCKER_REPO
    SAVE IMAGE $DOCKER_REPO/rust-env:$RELEASE$TAG_SUFFIX

vector:
    BUILD --build-arg DEBIAN_VERSION=$DEBIAN_VERSION --build-arg RELEASE=$RELEASE --build-arg TAG_SUFFIX=$TAG_SUFFIX --build-arg DOCKER_REPO=$DOCKER_REPO +basic-env
    FROM DOCKERFILE ./vector --RELEASE=$RELEASE --DOCKER_REPO=$DOCKER_REPO
    SAVE IMAGE $DOCKER_REPO/vector:$RELEASE$TAG_SUFFIX

# Level 2 dependencies (on k8s-cli)
eks:
    BUILD --build-arg DEBIAN_VERSION=$DEBIAN_VERSION --build-arg RELEASE=$RELEASE --build-arg TAG_SUFFIX=$TAG_SUFFIX --build-arg DOCKER_REPO=$DOCKER_REPO +k8s-cli
    FROM DOCKERFILE ./eks --RELEASE=$RELEASE --DOCKER_REPO=$DOCKER_REPO
    SAVE IMAGE $DOCKER_REPO/eks:$RELEASE$TAG_SUFFIX

all:
    BUILD --build-arg DEBIAN_VERSION=$DEBIAN_VERSION --build-arg RELEASE=$RELEASE --build-arg TAG_SUFFIX=$TAG_SUFFIX --build-arg DOCKER_REPO=$DOCKER_REPO +basic-env 
    BUILD --build-arg DEBIAN_VERSION=$DEBIAN_VERSION --build-arg RELEASE=$RELEASE --build-arg TAG_SUFFIX=$TAG_SUFFIX --build-arg DOCKER_REPO=$DOCKER_REPO +duckdb
    BUILD --build-arg DEBIAN_VERSION=$DEBIAN_VERSION --build-arg RELEASE=$RELEASE --build-arg TAG_SUFFIX=$TAG_SUFFIX --build-arg DOCKER_REPO=$DOCKER_REPO +mongo-client
    BUILD --build-arg DEBIAN_VERSION=$DEBIAN_VERSION --build-arg RELEASE=$RELEASE --build-arg TAG_SUFFIX=$TAG_SUFFIX --build-arg DOCKER_REPO=$DOCKER_REPO +mysql-cli
    BUILD --build-arg DEBIAN_VERSION=$DEBIAN_VERSION --build-arg RELEASE=$RELEASE --build-arg TAG_SUFFIX=$TAG_SUFFIX --build-arg DOCKER_REPO=$DOCKER_REPO +postgres-cli
    BUILD --build-arg DEBIAN_VERSION=$DEBIAN_VERSION --build-arg RELEASE=$RELEASE --build-arg TAG_SUFFIX=$TAG_SUFFIX --build-arg DOCKER_REPO=$DOCKER_REPO +python-3-env
    BUILD --build-arg DEBIAN_VERSION=$DEBIAN_VERSION --build-arg RELEASE=$RELEASE --build-arg TAG_SUFFIX=$TAG_SUFFIX --build-arg DOCKER_REPO=$DOCKER_REPO +k8s-cli
    BUILD --build-arg DEBIAN_VERSION=$DEBIAN_VERSION --build-arg RELEASE=$RELEASE --build-arg TAG_SUFFIX=$TAG_SUFFIX --build-arg DOCKER_REPO=$DOCKER_REPO +go-env
    BUILD --build-arg DEBIAN_VERSION=$DEBIAN_VERSION --build-arg RELEASE=$RELEASE --build-arg TAG_SUFFIX=$TAG_SUFFIX --build-arg DOCKER_REPO=$DOCKER_REPO +jsqsh
    BUILD --build-arg DEBIAN_VERSION=$DEBIAN_VERSION --build-arg RELEASE=$RELEASE --build-arg TAG_SUFFIX=$TAG_SUFFIX --build-arg DOCKER_REPO=$DOCKER_REPO +lua-5.4-env
    BUILD --build-arg DEBIAN_VERSION=$DEBIAN_VERSION --build-arg RELEASE=$RELEASE --build-arg TAG_SUFFIX=$TAG_SUFFIX --build-arg DOCKER_REPO=$DOCKER_REPO +node-14-env
    BUILD --build-arg DEBIAN_VERSION=$DEBIAN_VERSION --build-arg RELEASE=$RELEASE --build-arg TAG_SUFFIX=$TAG_SUFFIX --build-arg DOCKER_REPO=$DOCKER_REPO +node-16-env
    BUILD --build-arg DEBIAN_VERSION=$DEBIAN_VERSION --build-arg RELEASE=$RELEASE --build-arg TAG_SUFFIX=$TAG_SUFFIX --build-arg DOCKER_REPO=$DOCKER_REPO +rust-env
    BUILD --build-arg DEBIAN_VERSION=$DEBIAN_VERSION --build-arg RELEASE=$RELEASE --build-arg TAG_SUFFIX=$TAG_SUFFIX --build-arg DOCKER_REPO=$DOCKER_REPO +vector
    BUILD --build-arg DEBIAN_VERSION=$DEBIAN_VERSION --build-arg RELEASE=$RELEASE --build-arg TAG_SUFFIX=$TAG_SUFFIX --build-arg DOCKER_REPO=$DOCKER_REPO +eks
