name: Docker build (single-arch)
description: Checkout, setup Docker, login, and build+push a single-arch image via Makefile target

inputs:
  target:
    description: Makefile target (image directory name) to build
    required: true
  arch:
    description: Target architecture (amd64 or arm64)
    required: true
  dockerhub-username:
    description: Docker Hub username
    required: true
  dockerhub-token:
    description: Docker Hub token/password
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
    
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}

    - name: Build and push
      shell: bash
      run: |
        ARCHITECTURE=${{ inputs.arch }} make ${{ inputs.target }} -B -s
