# Set correct shell path
set -g default-command /usr/bin/zsh
set-option -g default-shell /usr/bin/zsh


# Enable Mouse
set -g mouse on

# Terminal settings
set -g default-terminal "xterm-256color"
set -gw xterm-keys on

# Start numbering from 1 and not 0

set -g base-index 1
set -g pane-base-index 1

# Prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Pane navigation
bind ] select-pane -t :.+
bind [ select-pane -t :.-

# Pane splits (stay in current dir)
unbind %
unbind '"'
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Windows
bind W confirm-before -p "kill-window #W? (y/n)" kill-window

# Sessions
bind S new-session
bind Q confirm-before -p "kill-session #S? (y/n)" kill-session
