"$schema" = 'https://starship.rs/config-schema.json' # Get editor completions based on the config schema

add_newline = true # Inserts a blank line between shell prompts

format = """
$fill  \
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\

$golang\
$java\
$gradle\
$kotlin\
$nodejs\
$python\
$helm\
$terraform\

${custom.workspace}\

$kubernetes\
$aws\
$gcloud \
$fill\
$line_break\
$sudo\
$cmd_duration\
$status\
$directory\
$jobs\
$battery\
$character"""

[custom.workspace]
command = 'echo Container: ${WORKSPACE_NAME}'
when = true
format = '\[[$output]($style)\]'
style = 'bold green'

[status]
disabled = true

[battery]
format = '\[[$symbol$percentage]($style)\]'

[[battery.display]]
threshold = 20
style = "bold red"

[directory]
before_repo_root_style = "bold #FFFFFF"
repo_root_style = "bold #00FF00"
truncate_to_repo = false
truncation_length = 7
truncation_symbol = "…/"

[fill]
symbol = '-'
style = 'white'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'
symbol = 'A '

[cmd_duration]
min_time = 500
format = '\[[⏱ $duration]($style)\] '

[gcloud]
symbol = 'G '
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\] '

[git_branch]
format = '\[[$symbol$branch]($style)\]'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
format = '\[[$symbol($version)]($style)\]'

[gradle]
format = '\[[$symbol($version)]($style)\]'

[helm]
format = '\[[$symbol($version)]($style)\]'

[java]
format = '\[[$symbol($version)]($style)\]'
style = "bold #d2691e"

[kotlin]
format = '\[[$symbol($version)]($style)\]'

[kubernetes]
symbol = 'K '
disabled = false
format = '\[[$symbol$context( \($namespace\))]($style)\]'
style = "bold blue"

[nodejs]
format = '\[[$symbol($version)]($style)\]'

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[rust]
format = '\[[$symbol($version)]($style)\]'

[scala]
format = '\[[$symbol($version)]($style)\]'

[swift]
format = '\[[$symbol($version)]($style)\]'

[terraform]
format = '\[[$symbol$version]($style)\]'
detect_extensions = ["tf", "hcl", "tfvars", "tfstate"]

[time]
format = '\[[$time]($style)\]'

[username]
format = '\[[$user]($style)\]'
