#!/bin/sh

function help {
    if [[ -z "${SCRIPT}" ]];
    then
        SCRIPT=`basename $0`
    fi
    printf "\n"
    printf "Usage:\n"
    printf "\t${SCRIPT} [-flags]"
    printf "\n"
    printf "Mandatory Flags:\n"
    printf "\t-w, --workspace-name:\n"
    printf "\tThe name of the Workspace (creates new or uses existing).\n"
    printf "\n"
    printf "\t-r, --aws-region:\n"
    printf "\tThe AWS Region the cluster is located in.\n"
    printf "\n"
    printf "\t-p, --aws-profile:\n"
    printf "\tThe AWS Profile being used.\n"
    printf "\n"
    printf "\t-c, --cluster-name:\n"
    printf "\tThe Name of the EKS cluster to connect to.\n"
    printf "\n"
    printf "Optional Flags:\n"
    printf "\t-j, --project-dir:\n"
    printf "\tThe local directory to map as a project directory.\n"
    printf "\n"
    printf "Examples:\n"
    printf "\t# Connects to a dev cluster\n"
    printf "\t${SCRIPT} -w 'EKS Dev' -r 'us-east-1' -c 'MyDevCluster'\n"
    printf "\n"
    printf "\t# Connects to a dev cluster with the current dir as a project dir\n"
    printf "\t${SCRIPT} -w 'EKS Dev' -r 'us-east-1' -c 'MyDevCluster' -j .\n"
    printf "\n"
    exit 1
}

copy_aws_item() {
    local src_path="$1"
    local dest_path="$2"

    if [[ -d "${src_path}" ]];
    then
        mkdir -p "${dest_path}"
        cp -RL "${src_path}/." "${dest_path}/"
    elif [[ -f "${src_path}" || -L "${src_path}" ]];
    then
        mkdir -p "$(dirname "${dest_path}")"
        cp -L "${src_path}" "${dest_path}"
    fi
}

for arg in "$@"; do
  shift
  case "$arg" in
    '--help')            set -- "$@" '-h'   ;;
    '--workspace-name')  set -- "$@" '-w'   ;;
    '--aws-region')      set -- "$@" '-r'   ;;
    '--aws-profile')     set -- "$@" '-p'   ;;
    '--cluster-name')    set -- "$@" '-c'   ;;
    '--project-dir')     set -- "$@" '-j'   ;;
    *)                   set -- "$@" "$arg" ;;
  esac
done

while getopts ":w:p:r:c:j:h:" option; do
    case "${option}" in
        h)
            help
            ;;
        w)
            export WORKSPACE_NAME=${OPTARG}
            ;;
        r)
            export AWS_REGION=${OPTARG}
            ;;
        p)
            export AWS_PROFILE=${OPTARG}
            ;;
        c)
            export CLUSTER_NAME=${OPTARG}
            ;;
        j)
            export PROJECT_DIR=${OPTARG}
            PROJECT_PARTITION=" -v ${PROJECT_DIR}:/root/proj/"
            MOUNT_POINT=" --mount ${PROJECT_DIR}"
            ;;
        *)
            printf "${BRIGHT}The flag ${RED}${option}${WHITE} is not supported provided!${NORMAL}\n"
            help
            ;;
    esac
done
shift $((OPTIND-1))

if [[ -z "${WORKSPACE_NAME}" ]];
then
    printf "${BRIGHT}${RED}Workspace Name was not provided!${NORMAL}\n"
    help
fi

if [[ -z "${AWS_PROFILE}" ]];
then
    printf "${BRIGHT}${RED}AWS Profile was not provided!${NORMAL}\n"
    help
fi

if [[ -z "${AWS_REGION}" ]];
then
    printf "${BRIGHT}${RED}AWS Region was not provided!${NORMAL}\n"
    help
fi

if [[ -z "${CLUSTER_NAME}" ]];
then
    printf "${BRIGHT}${RED}Cluster Name was not provided!${NORMAL}\n"
    help
fi

AWS_SOURCE_DIR="${HOME}/.aws"
if [[ ! -d "${AWS_SOURCE_DIR}" ]];
then
    printf "${BRIGHT}${RED}AWS config directory was not found at ${AWS_SOURCE_DIR}!${NORMAL}\n"
    exit 1
fi

export IMAGE="${MY_DOCKER_IMAGES_REPO}/eks:$(cat ${HOME}/.my-docker-images.release)"
WORKSPACE_HUMAN_NAME="${WORKSPACE_NAME}"

WORKSPACE_BUILDER_ARGS=(-i "${IMAGE}" -w "${WORKSPACE_HUMAN_NAME}")
if [[ -n "${PROJECT_DIR}" ]];
then
    WORKSPACE_BUILDER_ARGS+=(-m "${PROJECT_DIR}")
fi

source "_docker_workspace_builder" "${WORKSPACE_BUILDER_ARGS[@]}"

AWS_WORKSPACE_CONFIG_DIR="${WORKSPACE_DIR}/.aws"
rm -rf "${AWS_WORKSPACE_CONFIG_DIR}"
mkdir -p "${AWS_WORKSPACE_CONFIG_DIR}"
copy_aws_item "${AWS_SOURCE_DIR}/config" "${AWS_WORKSPACE_CONFIG_DIR}/config"
copy_aws_item "${AWS_SOURCE_DIR}/cli" "${AWS_WORKSPACE_CONFIG_DIR}/cli"
copy_aws_item "${AWS_SOURCE_DIR}/sso" "${AWS_WORKSPACE_CONFIG_DIR}/sso"
mkdir -p "${WORKSPACE_DIR}/.kube"

_docker_run_it \
    --image ${IMAGE} \
    --workspace-name "${WORKSPACE_HUMAN_NAME}" \
    ${MOUNT_POINT} \
    --extra-params " -v ${AWS_WORKSPACE_CONFIG_DIR}:/root/.aws \
    -v ${WORKSPACE_DIR}/.kube:/root/.kube \
    --env AWS_PROFILE=${AWS_PROFILE} \
    --env AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
    --env AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
    --env AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN} \
    --env AWS_REGION=${AWS_REGION} \
    --env EKS_CLUSTER=${CLUSTER_NAME}"
