#!/bin/sh

export SCRIPT=`basename $0`; 
export IMAGE=lua-5.4-env;
_docker_run_it --image "${MY_DOCKER_IMAGES_REPO}/${IMAGE}:$(cat ${HOME}/.my-docker-images.release)" "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9"