#!/bin/sh

#DOC# MySQL;mysqlenv;Launches a docker container connected to a specific MySQL database

function help {
    if [[ -z "${SCRIPT}" ]];
    then
        SCRIPT=`basename $0`
    fi
    printf "\n"
    printf "Usage:\n"
    printf "\t${SCRIPT} [-flags]"
    printf "\n"
    printf "Mandatory Flags:\n"
    printf "\t-w, --workspace-name:\n"
    printf "\tThe name of the Workspace (creates new or uses existing).\n"
    printf "\n"
    printf "\t-s, --db-server:\n"
    printf "\tThe Database Server to connect to.\n"
    printf "\n"
    printf "\t-n, --db-name:\n"
    printf "\tThe Name of the Database to connect to.\n"
    printf "\n"
    printf "\t-o, --db-port:\n"
    printf "\tThe Port of the Database to connect to.\n"
    printf "\n"
    printf "\t-u, --username:\n"
    printf "\tThe Username to connect with.\n"
    printf "\n"
    printf "\t-p, --password:\n"
    printf "\tThe Password to connect with.\n"
    printf "\n"
    printf "Examples:\n"
    printf "\t# Connects to a server\n"
    printf "\t${SCRIPT} -w 'My DB' -s mysql.server.com -n mydb -o 3361 -u myuser -p secretpassword\n"
    printf "\n"
    exit 1
}

for arg in "$@"; do
  shift
  case "$arg" in
    '--help')            set -- "$@" '-h'   ;;
    '--workspace-name')  set -- "$@" '-w'   ;;
    '--db-server')       set -- "$@" '-s'   ;;
    '--db-port')         set -- "$@" '-o'   ;;
    '--db-name')         set -- "$@" '-n'   ;;
    '--username')        set -- "$@" '-u'   ;;
    '--password')        set -- "$@" '-p'   ;;
    *)                   set -- "$@" "$arg" ;;
  esac
done

while getopts ":w:s:o:n:u:p:h:" option; do
    case "${option}" in
        h)
            help
            ;;
        w)
            export WORKSPACE_NAME=${OPTARG}
            ;;
        s)
            export MYSQL_HOSTNAME=${OPTARG}
            ;;
        o)
            export MYSQL_PORT=${OPTARG}
            ;;
        n)
            export MYSQL_DB=${OPTARG}
            ;;
        u)
            export MYSQL_USERNAME=${OPTARG}
            ;;
        p)
            export MYSQL_PASSWORD=${OPTARG}
            ;;
        *)
            printf "${BRIGHT}The flag ${RED}${option}${WHITE} is not supported provided!${NORMAL}\n"
            help
            ;;
    esac
done
shift $((OPTIND-1))

if [[ -z "${WORKSPACE_NAME}" ]];
then
    printf "${BRIGHT}${RED}Workspace Name was not provided!${NORMAL}\n"
    help
fi

if [[ -z "${MYSQL_HOSTNAME}" ]];
then
    printf "${BRIGHT}${RED}DB Host was not provided!${NORMAL}\n"
    help
fi

if [[ -z "${MYSQL_DB}" ]];
then
    printf "${BRIGHT}${RED}DB Name was not provided!${NORMAL}\n"
    help
fi

if [[ -z "${MYSQL_PORT}" ]];
then
    printf "${BRIGHT}${RED}DB Port was not provided!${NORMAL}\n"
    help
fi

if [[ -z "${MYSQL_USERNAME}" ]];
then
    printf "${BRIGHT}${RED}User Name was not provided!${NORMAL}\n"
    help
fi

if [[ -z "${MYSQL_PASSWORD}" ]];
then
    printf "${BRIGHT}${RED}Password was not provided!${NORMAL}\n"
    help
fi

export IMAGE_NAME=mysql-cli;
export IMAGE="${MY_DOCKER_IMAGES_REPO}/${IMAGE_NAME}:$(cat ${HOME}/.my-docker-images.release)"

_docker_run_it \
    --image "${IMAGE}" \
    --workspace-name "${WORKSPACE_NAME}" \
    --extra-params "--env MYSQL_PASSWORD=${MYSQL_PASSWORD} \
    --env MYSQL_HOSTNAME=${MYSQL_HOSTNAME} \
    --env MYSQL_PORT=${MYSQL_PORT} \
    --env MYSQL_DB=${MYSQL_DB} \
    --env MYSQL_USERNAME=${MYSQL_USERNAME} "
