#!/bin/sh

#DOC# Python;py3env;Opens a python 3.xx docker container with an optional mount point

export SCRIPT=`basename $0`;
export IMAGE=python-3-env;
_docker_run_it --image "${MY_DOCKER_IMAGES_REPO}/${IMAGE}:$(cat ${HOME}/.my-docker-images.release)" "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9"
