name: Docker manifest (multi-arch)
description: Checkout, setup Docker, login, and create+push a multi-arch manifest via Makefile target

inputs:
  target:
    description: Makefile target (image directory name) for which to create a manifest
    required: true
  dockerhub-username:
    description: Docker Hub username
    required: true
  dockerhub-token:
    description: Docker Hub token/password
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}

    - name: Create and push manifest
      shell: bash
      run: |
        make ${{ inputs.target }}-manifest -B -s
